{
 "title": "NV-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "nv_summary_hosts", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Controllers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "nv_summary_controllers", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Enforcers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "nv_summary_enforcers", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "nv_summary_pods", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Disconnected Enforcers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "nv_summary_disconnectedEnforcers",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Traffics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "bytes per minute" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nv_conversation_bytes[1m]))*4",
     "legendFormat": "bytes per minute"
    }
   ]
  },
  {
   "title": "Allowed Admissions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nv_admission_allowed", "legendFormat": "{{target}}:allowed" }
   ]
  },
  {
   "title": "Denied Admissions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nv_admission_denied" }
   ]
  },
  {
   "title": "CVEDB Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "nv_summary_cvedbVersion", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "CVEDB Create Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 3 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    { "expr": "nv_summary_cvedbTime", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "nv_enforcer_cpu", "legendFormat": "{{display}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "nv_enforcer_memory", "legendFormat": "{{display}}" }
   ]
  },
  {
   "title": "Service Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(nv_container_vulnerabilityHigh) by (service)"
    },
    {
     "expr": "sum(nv_container_vulnerabilityMedium) by (service)"
    }
   ]
  },
  {
   "title": "Image Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(nv_image_vulnerabilityHigh) by (name)"
    },
    {
     "expr": "sum(nv_image_vulnerabilityMedium) by (name)"
    }
   ]
  },
  {
   "title": "Security Events",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "nv_log_events",
     "legendFormat": "<font color=\"red\">{{name}}</font><br/>{{fromname}}<br/>-> {{toname}}"
    }
   ]
  }
 ]
}