# NV Exporter Conf File - Using Secrets/ConfigMap
# Use config map for not-secret configuration data
apiVersion: v1
kind: ConfigMap
metadata:
  name: nv-exporter-cm
data:
  CTRL_API_SERVICE: neuvector-svc-controller.neuvector:10443
  EXPORTER_PORT: '8068'

---
# Use secrets for things which are actually secret like API keys, credentials, etc
# echo -n 'admin' | base64
apiVersion: v1
kind: Secret
metadata:
  name: nv-exporter-secret
type: Opaque
data:
  CTRL_USERNAME: YWRtaW4=
  CTRL_PASSWORD: YWRtaW4=

---
apiVersion: v1
kind: Service
metadata:
  name: neuvector-svc-prometheus-exporter
  namespace: neuvector
spec:
  ports:
    - port: 8068
      name: prometheus-exporter
      protocol: TCP
  selector:
    app: neuvector-prometheus-exporter-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-prometheus-exporter-pod
  namespace: neuvector
spec:
  selector:
    matchLabels:
      app: neuvector-prometheus-exporter-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: neuvector-prometheus-exporter-pod
    spec:
      containers:
        - name: neuvector-prometheus-exporter-pod
          image: neuvector/prometheus-exporter
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
             name: nv-exporter-cm
          - secretRef:
             name: nv-exporter-secret
          # env vars - only for test cases
          # env:
          #   - name: CTRL_API_SERVICE
          #     value: neuvector-svc-controller.neuvector:10443
          #   - name: CTRL_USERNAME
          #     value: admin
          #   - name: CTRL_PASSWORD
          #     value: admin
          #   - name: EXPORTER_PORT
          #     value: "8068"
      restartPolicy: Always
