apiVersion: v1
kind: Service
metadata:
  name: neuvector-svc-prometheus-exporter
  namespace: neuvector
spec:
  ports:
    - port: 8068
      name: prometheus-exporter
      protocol: TCP
  selector:
    app: neuvector-prometheus-exporter-pod

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: neuvector-prometheus-exporter-pod
  namespace: neuvector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neuvector-prometheus-exporter-pod
    spec:
      containers:
        - name: neuvector-prometheus-exporter-pod
          image: neuvector/prometheus-exporter
          imagePullPolicy: Always
          env:
            - name: CTRL_API_SERVICE
              value: neuvector-svc-controller.neuvector:10443
            - name: CTRL_USERNAME
              value: admin
            - name: CTRL_PASSWORD
              value: admin
            - name: EXPORTER_PORT
              value: "8068"
      restartPolicy: Always
