apiVersion: v1
kind: Service
metadata:
  name: neuvector-svc-prometheus-exporter
  namespace: neuvector
spec:
  ports:
    - port: 8068
      name: prometheus-exporter
      protocol: TCP
  selector:
    app: neuvector-prometheus-exporter-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-prometheus-exporter-pod
  namespace: neuvector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuvector-prometheus-exporter-pod
  template:
    metadata:
      labels:
        app: neuvector-prometheus-exporter-pod
    spec:
      containers:
        - name: neuvector-prometheus-exporter-pod
          image: neuvector/prometheus-exporter:1.0.2
          imagePullPolicy: Always
          env:
            - name: CTRL_API_SERVICE
              value: neuvector-svc-controller.neuvector:10443
            - name: CTRL_USERNAME
              value: admin
            - name: CTRL_PASSWORD
              value: admin
            - name: EXPORTER_PORT
              value: "8068"
            # - name: EXPORTER_METRICS
            #   value: summary,conversation,enforcer,host,admission,image_vulnerability,container_vulnerability,log
      restartPolicy: Always
